apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster0
  region: ap-northeast-2
  version: "1.31"

vpc:
  subnets:
    public:
      ap-northeast-2a:
        id: subnet-03a152f4da858cb21
      ap-northeast-2c:
        id: subnet-037c0459e77fe1a1c
    private:
      ap-northeast-2a:
        id: subnet-0b24dde45eadbf699
      ap-northeast-2c:
        id: subnet-03cebf3d0206398d8

managedNodeGroups:
  - name: eks-cluster0-ng0
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    amiFamily: AmazonLinux2
