apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-svc-sync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wild-mental/gitops_msa_main.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
